#!/usr/bin/env bash

_PAVULLMO_CONFIG_DIR="$({ cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd; })"
source "${_PAVULLMO_CONFIG_DIR}/20m_config.sh"
unset _PAVULLMO_CONFIG_DIR

export VOCAB_SIZE=16384
export DATASET_PREFIX=16k
export ROPE_BASE=10000.0
export INITIALIZATION=gpt_scaled
export INITIALIZATION_STD=0.02
export QK_NORM=true
export SPLIT_QKV_PROJECTIONS=true

export LR=0.00230
export MIN_LR=0.0
export LR_SCHEDULER=wsd
export WSD_DECAY_FRACTION=0.40
export WARMUP_STEPS=219

export ADAM_BETA1=0.9
export ADAM_BETA2=0.99
export ADAM_EPS=1e-8
export BATCH_SIZE=16
export GRAD_ACCUM_STEPS=1
export WEIGHT_DECAY=0.10
export MAX_GRAD_NORM=1.0
export MUON_LR_MULTIPLIER=0.5
export MUON_WEIGHT_DECAY=0.1

export DROPOUT=0.0
export Z_LOSS_COEFFICIENT=0.0
export VALIDATION_INTERVAL=149
export VALIDATION_STEPS=7
export DIAGNOSTICS_INTERVAL=30
